### ISSUE TITLE
verify eliza-twitter integration

### ISSUE THREAD

**Issue by zenghbo** [0glabs/0g-serving-broker#80]

**Comment by roybein** [comment]
eliza tag v0.1.5-alpha.5 basicly works.
With local ollma as model provider, I can chat with eliza in CLI.

twitter client not work yet
1. I set up twitter account info and test in eliaz
2. standalone test with code to use package agent-twitter-client
1 & 2 both failed at auth, seems network problem or X API v1.1 and v2 issue.

rumor about X api version
https://devcommunity.x.com/t/v1-1-api-no-longer-working/199890/3

**Comment by roybein** [comment]
1. twitter client works with correct env and good network( or fixed local proxy of agent-twitter-client)
2. agent use LLM generate post and send tweet works.
3. agent throw errors when checked the interactive from twitter (like tweet be replied).
4. direct message can not trigger agent.
